#!/bin/bash

GREEN='\033[0;32m'
BOLD='\033[1m'
NC='\033[0m'

#cd temp && rm -rf * && cmake .. && make && cd ..
if [ ! -d "temp" ]; then
  printf "${BOLD}Creating build directory${NC}\n"
  mkdir temp
fi

cd temp && rm -rf * && cmake .. && make && cd ..
printf "${BOLD}Build completed${NC}\n"
