#!/bin/bash

if [ "$1" = "clean" ]; then
  printf "${BOLD}Deleting build directory${NC}\n"
  rm -rf temp

  printf "${BOLD}Deleting cpp module${NC}\n"
  rm genetic_snake/*.so  
  
  exit 0
fi

BOLD='\033[1m'
NC='\033[0m'

if [ ! -d "temp" ]; then
  printf "${BOLD}Creating build directory${NC}\n"
  mkdir temp
fi

cd temp && cmake .. && make && cd ..
mv temp/cpp_module.cpython-38-x86_64-linux-gnu.so genetic_snake/cpp_module.cpython-38-x86_64-linux-gnu.so
printf "${BOLD}Build completed${NC}\n"
