#!/bin/bash

BOLD='\033[1m'
NC='\033[0m'

if [ ! -d "temp" ]; then
  printf "${BOLD}Creating build directory${NC}\n"
  mkdir temp
fi

cd temp && rm -rf * && cmake .. && make && cd ..
printf "${BOLD}Build completed${NC}\n"
